apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: activemqartemisscaledowns.broker.amq.io
spec:
  group: broker.amq.io
  names:
    kind: ActiveMQArtemisScaledown
    listKind: ActiveMQArtemisScaledownList
    plural: activemqartemisscaledowns
    singular: activemqartemisscaledown
  scope: Namespaced
  version: v2alpha1
  versions:
    - name: v2alpha1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          properties:
            apiVersion:
              type: string
            kind:
              type: string
            metadata:
              type: object
            spec:
              properties:
                localOnly:
                  description: 'If enabled, the controller only handles StatefulSets in a
                    single namespace instead of across all namespaces.'
                  type: boolean
              required:
                - localOnly
              type: object
            status:
              type: object
    - name: v1alpha1
      served: false
      storage: false
  subresources:
    status: {}
