apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: '2020-04-23T01:01:38Z'
  name: activemqartemisscaledowns.broker.amq.io
spec:
  group: broker.amq.io
  subresources:
    status: {}
  names:
    plural: activemqartemisscaledowns
    singular: activemqartemisscaledown
    kind: ActiveMQArtemisScaledown
    listKind: ActiveMQArtemisScaledownList
  scope: Namespaced
  conversion:
    strategy: None
  preserveUnknownFields: true
  version: v2alpha1
  validation:
    openAPIV3Schema:
      type: object
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
          required:
            - localOnly
          properties:
            localOnly:
              description: >-
                If enabled, the controller only handles StatefulSets in a single
                namespace instead of across all namespaces.
              type: boolean
        status:
          type: object
  versions:
    - name: v2alpha1
      served: true
      storage: true
    - name: v1alpha1
      served: false
      storage: false
