apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  name: activemq-artemis-operator.v0.9.2
  namespace: site1
  annotations:
    categories: "Streaming & Messaging"
    certified: "false"
    description: Extends the AMQ Broker Operator to provide asynchronous replication between sites for continuity.
    containerImage: quay.io/jowest/activemq-artemis-operator:0.2
    createdAt: 2020-03-19T08:16:32Z
    capabilities: Basic Install
    repository: https://github.com/shuawest/activemq-artemis-operator
    support: N/A
    tectonic-visibility: ocs
    alm-examples: >-
      [{
          "apiVersion": "broker.amq.io/v2alpha1",
          "kind": "ActiveMQArtemis",
          "metadata": {
              "name": "ex-aao"
          },
          "spec": {
              "deploymentPlan": {
                  "size": 1,
                  "image": "quay.io/jowest/activemq-artemis-openshift:0.2"
              }
          }
      },
      {
          "apiVersion": "broker.amq.io/v2alpha1",
          "kind": "ActiveMQArtemisAddress",
          "metadata": {
              "name": "ex-aaoaddress"
          },
          "spec": {
              "addressName": "myAddress0",
              "queueName": "myQueue0",
              "routingType": "anycast"
          }
      },
      {
          "apiVersion": "broker.amq.io/v2alpha1",
          "kind": "ActiveMQArtemisScaledown",
          "metadata": {
              "name": "ex-aaoscaledown"
          },
          "spec": {
              "localOnly": "true"
          }
      }]
labels:
  operator-activemqartemis: "true"
spec:
  displayName: AMQ Broker Continuity
  description: Extends the AMQ Broker Operator to provide asynchronous replication between sites for continuity.
  keywords:
    - activemqartemis
    - operator
    - continuity
  version: 0.9.2
  maturity: alpha
  source: community-operators
  maintainers:
    - name: Red Hat, Inc.
      email: jowest@redhat.com
  provider:
    name: N/A
  links:
    - name: Product Page
      url: https://access.redhat.com/products/red-hat-amq/
    - name: Documentation
      url: https://access.redhat.com/documentation/en-us/red_hat_amq/
    - name: Continuity
      url: https://github.com/shuawest/artemis-continuity-plugin
  icon:
    - base64data: iVBORw0KGgoAAAANSUhEUgAAACAAAAAgCAYAAABzenr0AAAABGdBTUEAALGPC/xhBQAAAAZiS0dEAP8A/wD/oL2nkwAAAAlwSFlzAAAlywAAJcsBGkdkZgAAAAd0SU1FB+MDHQ02AU8UBK4AAASBSURBVFjDtZfNb1RlFMZ/7zt3vqCU0pSSQjMSbCHVRSEjq7aBhQvFsDBqJIYF/gGGxAUpREyMCG5YqCSuiDGGRE2NCxTRBgkJuGlKYpAOBW3NtJ22UzoznTv3du6d++FibsvQ6XzQ1rO899z3Oefc5zznvII6LRahCTgCHAIOAu3ANu91GpgEhoBbwLWuOJl6zhV1AO8F+oG3gU11xqsD3wMXuuI8XFMAsQhh4BzwHuBnbVYAvgDOdsXR6w4gFqET+BF4kY2x+8DrXXEe1QwgFuEA8CuwnY21Od3h1egkwxUD8DK/8z+AozugOaQl9PQmiJUF4P3zoQ0s+0rwJRv1QbQngQaglPidqwYuWjtp+eRzELIqmF0wyefzy7kVcira6XdLXfY58KlH7qKX12p/VWO7cvA1OgZ+wrVthM+HY1lIRXnKx7EsMpkMOVXFJ8AwDMJ+P3/3daw8zpLQ3ZtgZCmd0/W22r/jY6jpFLdv/o6xuFgGbrsuqqqyuJDhcTJZMR8XzgAIT+GmaonMcgUsC6H4sAsWPr+/DBxgMaciERhGnk2BwGoVAMj7BO2KJ681Fc6ZHCd18waIculYXFjAdoosU/buI9y6Ayu7gDUyQjqnVjoy5LgcVYDD9ZTemR4heeLlmmxvvHydzaEw8Y/OYt74ttaxhxTgpdIn4eOnCHR0epS2KmusrmOXyEh28Be0u4OEZmeYv/J1PeC4EFW8qbZszW8dY8v+A1U/zGsaqpYjr+lIn8QfDKEWTLg7yHz/ibr1QUBEKRmpT/6pmiWZTBIIhjBNk+f27CkBz6FqOq5tMzUxQbChgdYdO9YkUC40KquyY3MDO3cFED6J67hl4AiBkJKtzdtQAkGklGtWSQVIAa3L2T8aRQYDBNt2oTQ14Zgm2v17WKaJlsvhel1guRD2vjFmZzDj8WcGF5AVsQh3gbKfrvS+SeSzLxE+H//sb66m7euxe4o3gMoCsG4PED8JbR9+7EUUJHzsJKaU+FxorDgMbArGk1ng6BrG1cuVKjAsYhHeAa5ULFOgAdfMoRw8QsfAzzVY5ZJNp9GNPAKBbdtI0+RR3/OVAjghgWveDrf6mWauSEAvo+nJCbRslj+HhjAN42nwTBrDtpmfe4yanGFyfKxqN0vBVeltr9/VUjjda4amrU2EwmEiu3fj92ZBETyDYdkABPx+lGCIcDhcjYA/9EyRWmrDC8Dx1SbiEuH8mRT67AwCganrhID83BwA2kKGfKFQpMqWRppaWnAdG7/jYCRnV8O3BJxfuRFdBN5fL9vbvrpOY3c301e+IXvxVKXsL/UligtJqYJ84G2v62o117KqggOjUtBfaSntAP7QHbavtc/lnijO2HCl1ylvKX1QcS0fbieqOfwGNG/wbpqS8EpvgqGnAl7pFZ1kWEIPMLqB4KNe5kNlFVvNuzfBA0UQFcVrlbUOYEvAJQWipWV/psvp7Z284MIZF94AQnUCGwIGBJzvTTCyrtvxkt3ZRbPjchQ47EJUQGRpJAjIuhAXMAzckoKrPVPM13Puf2Qd6X5KXrjXAAAAAElFTkSuQmCC
      mediatype: image/png
  labels:
    alm-owner-amq-broker: activemq-artemis-operator
    operated-by: activemq-artemis-operator.v0.9.2
  selector:
    matchLabels:
      ActiveMQArtemis: ex-aao
      application: ex-aao-app
      operated-by: activemq-artemis-operator.v0.9.2
  installModes:
    - type: OwnNamespace
      supported: true
    - type: SingleNamespace
      supported: false
    - type: MultiNamespace
      supported: false
    - type: AllNamespaces
      supported: false
  customresourcedefinitions:
    owned:
      - name: activemqartemises.broker.amq.io
        version: v2alpha1
        versions:
          - name: v2alpha1
            served: true
            storage: true
          - name: v1alpha1
            served: false
            storage: false
        kind: ActiveMQArtemis
        description: An instance of Active MQ Artemis
        displayName: AMQ Broker with Continuity
        resources:
          - kind: Service
            version: v1
          - kind: Route
            version: v1
          - kind: StatefulSet
            version: v1
          - kind: Secret
            version: v1
        specDescriptors:
          - description: User name for standard broker user. It is required for connecting to the broker and the web console. If left empty, it will be generated.
            displayName: AdminUser
            path: adminUser
          - description: Password for standard broker user. It is required for connecting to the broker and the web console. If left empty, it will be generated.
            displayName: AdminPassword
            path: adminPassword
          - description: The number of broker pods to deploy
            displayName: Size
            path: size
          - description: The image used for the broker deployment
            displayName: Image
            path: image
          - description: If true require user password login credentials for broker protocol ports
            displayName: RequireLogin
            path: requireLogin
          - description: If true use persistent volume via persistent volume claim for journal storage
            displayName: PersistenceEnabled
            path: persistenceEnabled
          - description: If aio use ASYNCIO, if nio use NIO for journal IO
            displayName: JournalType
            path: journalType
          - description: If true migrate messages on scaledown
            displayName: MessageMigration
            path: messageMigration
          - description: Whether or not to enable the continuity plugin. See required fields for continuity.
            displayName: EnableContinuity
            path: enableContinuity
          - description: Name the continuity site. Must be unique in the set of peers (is same across the artemis cluster). Required for continuity.
            displayName: SiteId
            path: siteId
          - description: Username to connect to the peer site broker/cluster for continuity connections. Required for continuity.
            displayName: PeerSiteUrl
            path: peerSiteUrl
          - description: Size of the broker id cache size, used by the broker to remove duplicate messages across sites. Make sure the id cache is sufficiently sized for your volume of messages. The default is 3000.
            displayName: BrokerIdCacheSize
            path: brokerIdCacheSize
          - description: Username to connect to the local broker for continuity connections. Required for continuity.
            displayName: LocalContinuityUser
            path: localContinuityUser
          - description: Password to connect to the local broker for continuity connections. Required for continuity.
            displayName: LocalContinuityPass
            path: localContinuityPass
          - description: Username to connect to the peer site broker/cluster for continuity connections. Required for continuity.
            displayName: RemoteContinuityUser
            path: remoteContinuityUser
          - description: Password to connect to the peer site broker/cluster for continuity connections. Required for continuity.
            displayName: RemoteContinuityPass
            path: remoteContinuityPass
          - description: Identifies this is the site that should be active when first started. If another active site is connected to, this site will defer to the other. You can also start both sites inactive and explictly activate the desired start. Required for continuity.
            displayName: ActiveOnStart
            path: activeOnStart
          - description: Bridge reconnection interval for all the bridges created by the continuity plugin. The default is 1000 ms or 1 second.
            displayName: BridgeInterval
            path: bridgeInterval
          - description: Bridge reconnection interval backoff multiplier for all the bridges created by the continuity plugin. The default is 0.5.
            displayName: BridgeIntervalMultiplier
            path: bridgeIntervalMultiplier
          - description: Amount of time in millseconds to delay messages in the inflow staging queues before delivering them to the target queues. Useful for active:active site topologies. The default is 1 minute.
            displayName: InflowStagingDelay
            path: inflowStagingDelay
          - description: Amount of time in millseconds to delay messages in the inflow staging queues before delivering them to the target queues. Useful for active:active site topologies. The default is 1 minute.
            displayName: InflowStagingDelay
            path: inflowStagingDelay
          - description: Time in milliseconds between polls to check for a site to be exhausted during deactivation. The default is 100 ms.
            displayName: OutflowExhaustedPollDuration
            path: outflowExhaustedPollDuration
          - description: Time in milliseconds between polls to check for a site to be consume all the acks during activation. The default is 100 ms.
            displayName: OutflowAcksConsumedPollDuration
            path: outflowAcksConsumedPollDuration
          - description: Time in milliseconds between polls to all the inflow acks have been consumed during activation. The default is 100 ms.
            displayName: InflowAcksConsumedPollDuration
            path: inflowAcksConsumedPollDuration
          - description: Time in milliseconds to activate a site and start serving clients, overriding the wait for the peer site to be exhausted, and acks to be consumed. The default is 300000 ms or 5 minutes.
            displayName: ActivationTimeout
            path: activationTimeout
          - description: Whether or not to reorganized all the address, queue, divert, and bridge primitives under the continuity hierarchy in JMX/Jolokia. The default is true.
            displayName: ReorgManagement
            path: reorgManagement
          - description: Logging level for the continuity plugin. The default is INFO.
            displayName: ContinuityLogLevel
            path: continuityLogLevel
      - name: activemqartemisaddresses.broker.amq.io
        version: v2alpha1
        kind: ActiveMQArtemisAddress
        description: Adding and removing addresses via custom resource definitions
        displayName: ActiveMQ Artemis Address
        specDescriptors:
          - description: The Queue Name
            displayName: Queue Name
            path: queueName
          - description: The Address Name
            displayName: Address Name
            path: addressName
          - description: The Routing Type
            displayName: Routing Type
            path: routingType
      - name: activemqartemisscaledowns.broker.amq.io
        version: v2alpha1
        kind: ActiveMQArtemisScaledown
        description: Provides message migration on clustered broker scaledown
        displayName: ActiveMQ Artemis Scaledown
        specDescriptors:
          - description: Triggered by main ActiveMQArtemis CRD messageMigration entry
            displayName: LocalOnly
            path: localOnly
  install:
    strategy: deployment
    spec:
      permissions:
        - serviceAccountName: activemq-artemis-operator
          rules:
            - apiGroups:
                - ""
              resources:
                - pods
                - services
                - endpoints
                - persistentvolumeclaims
                - events
                - configmaps
                - secrets
                - routes
              verbs:
                - '*'
            - apiGroups:
                - ""
              resources:
                - namespaces
              verbs:
                - get
            - apiGroups:
                - apps
              resources:
                - deployments
                - daemonsets
                - replicasets
                - statefulsets
              verbs:
                - '*'
            - apiGroups:
                - monitoring.coreos.com
              resources:
                - servicemonitors
              verbs:
                - get
                - create
            - apiGroups:
                - broker.amq.io
              resources:
                - '*'
              verbs:
                - '*'
            - apiGroups:
                - "route.openshift.io"
              resources:
                - routes
                - routes/custom-host
                - routes/status
              verbs:
                - get
                - list
                - watch
                - create
                - delete

      deployments:
        - name: activemq-artemis-operator
          spec:
            replicas: 1
            selector:
              matchLabels:
                name: activemq-artemis-operator
            template:
              metadata:
                labels:
                  name: activemq-artemis-operator
              spec:
                serviceAccountName: activemq-artemis-operator
                containers:
                  - name: activemq-artemis-operator
                    image: quay.io/jowest/activemq-artemis-operator:0.2
                    command:
                      -  /home/activemq-artemis-operator/bin/entrypoint
                    imagePullPolicy: Always
                    env:
                      - name: WATCH_NAMESPACE
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.namespace
                      - name: POD_NAME
                        valueFrom:
                          fieldRef:
                            fieldPath: metadata.name
                      - name: OPERATOR_NAME
                        value: "activemq-artemis-operator"
