apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: null
  name: activemqartemis.broker.amq.io
spec:
  group: broker.amq.io
  names:
    kind: ActiveMQArtemis
    listKind: ActiveMQArtemisList
    plural: activemqartemis
    singular: activemqartemis
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources'
          type: string
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          properties:
            acceptors:
              items:
                properties:
                  anycastPrefix:
                    type: string
                  connectionsAllowed:
                    format: int64
                    type: integer
                  enabledCipherSuites:
                    type: string
                  enabledProtocols:
                    type: string
                  expose:
                    type: boolean
                  multicastPrefix:
                    type: string
                  name:
                    type: string
                  needClientAuth:
                    type: boolean
                  port:
                    format: int32
                    type: integer
                  protocols:
                    type: string
                  sniHost:
                    type: string
                  sslEnabled:
                    type: boolean
                  sslProvider:
                    type: string
                  sslSecret:
                    type: string
                  verifyHost:
                    type: boolean
                  wantClientAuth:
                    type: boolean
                required:
                - name
                type: object
              type: array
            adminPassword:
              type: string
            adminUser:
              type: string
            connectors:
              items:
                properties:
                  enabledCipherSuites:
                    type: string
                  enabledProtocols:
                    type: string
                  expose:
                    type: boolean
                  host:
                    type: string
                  name:
                    type: string
                  needClientAuth:
                    type: boolean
                  port:
                    format: int32
                    type: integer
                  sniHost:
                    type: string
                  sslEnabled:
                    type: boolean
                  sslProvider:
                    type: string
                  sslSecret:
                    type: string
                  type:
                    type: string
                  verifyHost:
                    type: boolean
                  wantClientAuth:
                    type: boolean
                required:
                - name
                - host
                - port
                type: object
              type: array
            console:
              properties:
                expose:
                  type: boolean
                sslEnabled:
                  type: boolean
                sslSecret:
                  type: string
                useClientAuth:
                  type: boolean
              type: object
            deploymentPlan:
              properties:
                image:
                  type: string
                journalType:
                  type: string
                messageMigration:
                  type: boolean
                persistenceEnabled:
                  type: boolean
                requireLogin:
                  type: boolean
                size:
                  format: int32
                  type: integer
              type: object
            upgrades:
              properties:
                enabled:
                  type: boolean
                minor:
                  type: boolean
              required:
              - enabled
              - minor
              type: object
            version:
              type: string
          type: object
        status:
          properties:
            podStatus:
              description: 'INSERT ADDITIONAL STATUS FIELD - define observed state
                of cluster Important: Run "operator-sdk generate k8s" to regenerate
                code after modifying this file Add custom validation using kubebuilder
                tags: https://book.kubebuilder.io/beyond_basics/generating_crd.html'
              properties:
                ready:
                  description: Deployments are ready to serve requests
                  items:
                    type: string
                  type: array
                starting:
                  description: Deployments are starting, may or may not succeed
                  items:
                    type: string
                  type: array
                stopped:
                  description: Deployments are not starting, unclear what next step
                    will be
                  items:
                    type: string
                  type: array
              type: object
          required:
          - podStatus
          type: object
  version: v2alpha2
  versions:
  - name: v2alpha2
    served: true
    storage: true
  - name: v2alpha1
    served: true
    storage: false
  - name: v1alpha1
    served: false
    storage: false
