apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: activemqartemisscaledowns.broker.amq.io
spec:
  group: broker.amq.io
  names:
    kind: ActiveMQArtemisScaledown
    listKind: ActiveMQArtemisScaledownList
    plural: activemqartemisscaledowns
    singular: activemqartemisscaledown
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          properties:
            localOnly:
              type: boolean
          required:
          - localOnly
          type: object
        status:
          type: object
  version: v2alpha1
  versions:
  - name: v2alpha1
    served: true
    storage: true
