apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  creationTimestamp: '2020-04-23T01:01:38Z'
  name: activemqartemisaddresses.broker.amq.io
spec:
  group: broker.amq.io
  subresources:
    status: {}
  names:
    plural: activemqartemisaddresses
    singular: activemqartemisaddress
    kind: ActiveMQArtemisAddress
    listKind: ActiveMQArtemisAddressList
  scope: Namespaced
  conversion:
    strategy: None
  preserveUnknownFields: true
  version: v2alpha1
  validation:
    openAPIV3Schema:
      type: object
      properties:
        apiVersion:
          type: string
        kind:
          type: string
        metadata:
          type: object
        spec:
          type: object
          required:
            - addressName
            - queueName
            - routingType
          properties:
            addressName:
              type: string
            queueName:
              type: string
            routingType:
              type: string
        status:
          type: object
  versions:
    - name: v2alpha1
      served: true
      storage: true
    - name: v1alpha2
      served: true
      storage: false
    - name: v1alpha1
      served: false
      storage: false
