// +build !ignore_autogenerated

// Code generated by operator-sdk. DO NOT EDIT.

package v2alpha2

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveMQArtemisContinuity) DeepCopyInto(out *ActiveMQArtemisContinuity) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveMQArtemisContinuity.
func (in *ActiveMQArtemisContinuity) DeepCopy() *ActiveMQArtemisContinuity {
	if in == nil {
		return nil
	}
	out := new(ActiveMQArtemisContinuity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActiveMQArtemisContinuity) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveMQArtemisContinuityList) DeepCopyInto(out *ActiveMQArtemisContinuityList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ActiveMQArtemisContinuity, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveMQArtemisContinuityList.
func (in *ActiveMQArtemisContinuityList) DeepCopy() *ActiveMQArtemisContinuityList {
	if in == nil {
		return nil
	}
	out := new(ActiveMQArtemisContinuityList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ActiveMQArtemisContinuityList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveMQArtemisContinuitySpec) DeepCopyInto(out *ActiveMQArtemisContinuitySpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveMQArtemisContinuitySpec.
func (in *ActiveMQArtemisContinuitySpec) DeepCopy() *ActiveMQArtemisContinuitySpec {
	if in == nil {
		return nil
	}
	out := new(ActiveMQArtemisContinuitySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ActiveMQArtemisContinuityStatus) DeepCopyInto(out *ActiveMQArtemisContinuityStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ActiveMQArtemisContinuityStatus.
func (in *ActiveMQArtemisContinuityStatus) DeepCopy() *ActiveMQArtemisContinuityStatus {
	if in == nil {
		return nil
	}
	out := new(ActiveMQArtemisContinuityStatus)
	in.DeepCopyInto(out)
	return out
}
