apiVersion: broker.amq.io/v2alpha1
kind: ActiveMQArtemis
metadata:
  name: ex-aao
  application: ex-aao-app
spec:
  enableContinuity: true
  siteId: site1
  localContinuityUser: asdf
  localContinuityPass: asdfpass
  peerSiteUrl: amqp://peersiteuri/
  peerContinuityUser: zxcv
  peerContinuityPass: zxcvpass
  activeOnStart: true
  brokerIdCacheSize: 1000000
  inflowStagingDelay: 60000
  bridgeInterval: 1000
  bridgeIntervalMultiplier: 0.5
  outflowExhaustedPollDuration: 100
  inflowAcksConsumedPollDuration: 100
  activationTimeout: 300000
  reorgManagement: true
  continuityLogLevel: INFO
  deploymentPlan:
    size: 2
    image: registry.redhat.io/amq7/amq-broker:7.5
    requireLogin: false
    persistenceEnabled: false
    journalType: nio
    messageMigration: false
  console:
    expose: true
  acceptors:
    - name: amqp
      protocols: amqp
      port: 5672
      sslEnabled: true
      enabledCipherSuites: SSL_RSA_WITH_RC4_128_SHA,SSL_DH_anon_WITH_3DES_EDE_CBC_SHA
      enabledProtocols: TLSv1,TLSv1.1,TLSv1.2
      needClientAuth: true
      wantClientAuth: true
      verifyHost: true
      sslProvider: JDK
      sniHost: localhost
      expose: true
      anycastPrefix: jms.topic.
      multicastPrefix: /queue/
    - name: continuity
      protocols: amqp
      port: 5673
      sslEnabled: true
      enabledCipherSuites: SSL_RSA_WITH_RC4_128_SHA,SSL_DH_anon_WITH_3DES_EDE_CBC_SHA
      enabledProtocols: TLSv1,TLSv1.1,TLSv1.2
      needClientAuth: true
      wantClientAuth: true
      verifyHost: true
      sslProvider: JDK
      sniHost: localhost
      expose: true
  connectors:
    - name: connector0
      host: localhost
      port: 22222
      sslEnabled: true
      enabledCipherSuites: SSL_RSA_WITH_RC4_128_SHA,SSL_DH_anon_WITH_3DES_EDE_CBC_SHA
      enabledProtocols: TLSv1,TLSv1.1,TLSv1.2
      needClientAuth: true
      wantClientAuth: true
      verifyHost: true
      sslProvider: JDK
      sniHost: localhost
      expose: true
